name: Deploy Pi OLED
on: [push]
jobs:
  Deploy-Pi-OLED-Service:
    runs-on: [self-hosted, k3s]
    steps:
      - name: Git Pull
        run: cd /repos/pi-oled/ && git pull
      - name: Service Restart
        run: systemctl restart pi-oled
      - name: Service Status
        run: systemctl status pi-oled